version: "3"
services:
  redis:
    image: redis:latest
    network_mode: host
    ports:
      - 6379:6379

  mysql:
    image: mysql:5.7
    network_mode: host
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: article-service-username
      MYSQL_PASSWORD: article-service-password
      MYSQL_DATABASE: mysql_article_database
      MYSQL_ROOT_PASSWORD: rootpassword
  
  elasticsearch:
    image: elasticsearch:5.6.13
    network_mode: host
    ports: 
      - 9200:9200
